clippy_task:
    container:
        image: rustlang/rust:nightly
    component_script: rustup component add clippy
    update_script: cargo +nightly update
    toolchain_cache:
        folder: $RUSTUP_HOME
        fingerprint_script: rustc +nightly --version
    cargo_cache:
        folder: $CARGO_HOME/registry
        fingerprint_script: cat Cargo.lock
    fmt_script: cargo +nightly clippy

rustfmt_task:
    container:
        image: rustlang/rust:nightly
    component_script: rustup component add rustfmt
    fmt_script: cargo fmt --all -- --check

linux_task:
    matrix:
        - container:
            image: rust:latest
        - allow_failures: true
          container:
            image: rustlang/rust:nightly
    update_script: cargo update
    cargo_cache:
        folder: $CARGO_HOME/registry
        fingerprint_script: cat Cargo.lock
    build_script: cargo build
    test_script: cargo test
    before_cache_script: rm -rf $CARGO_HOME/registry/index
