[package]
name = "machine-id"
version = "0.1.0"
authors = ["Ben Boeckel <mathstuf@gmail.com>"]
license = "BSD"
description = """
Library to get a UUID specific to the machine.
"""

[dependencies]
lazy_static = "~0.1.14"
log = "~0.3.2"
#uuid = "~0.1.17"
# https://github.com/retep998/winapi-rs/issues/214
#winapi = "~0.2.4"
#advapi32-sys = "~0.1.2"

[dependencies.uuid]
git = "https://github.com/mathstuf/rust-uuid"
branch = "error-impl"
